// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnxTY5DR1l2mf3OxxvaEd-JqTx5Vzbm5U',
    appId: '1:179118638392:web:1ecd4a49e7fa54e9d7edcd',
    messagingSenderId: '179118638392',
    projectId: 'spotify-61b75',
    authDomain: 'spotify-61b75.firebaseapp.com',
    storageBucket: 'spotify-61b75.appspot.com',
    measurementId: 'G-VTM3QLZ97R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcOmut00RLz0FYk8PS3lcbUhBWd-nS8jU',
    appId: '1:179118638392:android:40496fb11f54a674d7edcd',
    messagingSenderId: '179118638392',
    projectId: 'spotify-61b75',
    storageBucket: 'spotify-61b75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfotYtUro3QYNAGw9LJ4CR5hP3TIVVXFM',
    appId: '1:179118638392:ios:048fc63888bbfda1d7edcd',
    messagingSenderId: '179118638392',
    projectId: 'spotify-61b75',
    storageBucket: 'spotify-61b75.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfotYtUro3QYNAGw9LJ4CR5hP3TIVVXFM',
    appId: '1:179118638392:ios:048fc63888bbfda1d7edcd',
    messagingSenderId: '179118638392',
    projectId: 'spotify-61b75',
    storageBucket: 'spotify-61b75.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnxTY5DR1l2mf3OxxvaEd-JqTx5Vzbm5U',
    appId: '1:179118638392:web:d909b27414024796d7edcd',
    messagingSenderId: '179118638392',
    projectId: 'spotify-61b75',
    authDomain: 'spotify-61b75.firebaseapp.com',
    storageBucket: 'spotify-61b75.appspot.com',
    measurementId: 'G-GJP8EL9802',
  );
}
